export const listings = [
  {
    id: "bh-001",
    name: "Casa Amihan",
    barangay: "Dahican",
    monthlyRent: 6500,
    maxOccupants: 4,
    utilitiesIncluded: false,
    estimatedUtilities: { electricity: 1400, water: 350, internet: 1200 },
    distanceToCampusKm: 3.2,
    fareOneWay: 15,
    amenities: ["Wi-Fi ready", "Kitchen", "Own CR"],
  },
  {
    id: "bh-002",
    name: "Marundan Student Residence",
    barangay: "Don Martin Marundan",
    monthlyRent: 4800,
    maxOccupants: 3,
    utilitiesIncluded: true,
    estimatedUtilities: { electricity: 0, water: 0, internet: 0 },
    distanceToCampusKm: 0.9,
    fareOneWay: 12,
    amenities: ["Wi-Fi included", "Shared CR", "Study area"],
  },
  {
    id: "bh-003",
    name: "Sainz Corner Dormitory",
    barangay: "Sainz",
    monthlyRent: 9000,
    maxOccupants: 6,
    utilitiesIncluded: false,
    estimatedUtilities: { electricity: 2100, water: 500, internet: 1500 },
    distanceToCampusKm: 1.6,
    fareOneWay: 12,
    amenities: ["Aircon", "Kitchen", "Laundry", "Parking"],
  },
  {
    id: "bh-004",
    name: "Matiao Garden Rooms",
    barangay: "Matiao",
    monthlyRent: 5200,
    maxOccupants: 2,
    utilitiesIncluded: false,
    estimatedUtilities: { electricity: 900, water: 250, internet: 0 },
    distanceToCampusKm: 2.4,
    fareOneWay: 13,
    amenities: ["Quiet street", "Own CR"],
  },
  {
    id: "bh-005",
    name: "Central Transient House",
    barangay: "Central",
    monthlyRent: 7400,
    maxOccupants: 5,
    utilitiesIncluded: false,
    estimatedUtilities: { electricity: 1800, water: 420, internet: 1300 },
    distanceToCampusKm: 1.1,
    fareOneWay: 12,
    amenities: ["Wi-Fi ready", "Kitchen", "Near market"],
  },
  {
    id: "bh-006",
    name: "Lopez Street Boarding House",
    barangay: "Don Enrique Lopez",
    monthlyRent: 4200,
    maxOccupants: 4,
    utilitiesIncluded: false,
    estimatedUtilities: { electricity: 1100, water: 300, internet: 0 },
    distanceToCampusKm: 2.0,
    fareOneWay: 13,
    amenities: ["Shared CR", "Curfew 10PM"],
  },
  {
    id: "bh-007",
    name: "Seaview Ladies Dorm",
    barangay: "Dahican",
    monthlyRent: 8200,
    maxOccupants: 4,
    utilitiesIncluded: true,
    estimatedUtilities: { electricity: 0, water: 0, internet: 0 },
    distanceToCampusKm: 3.6,
    fareOneWay: 15,
    amenities: ["Aircon", "Wi-Fi included", "Ladies only", "Laundry"],
  },
  {
    id: "bh-008",
    name: "Macambol Hillside Rooms",
    barangay: "Macambol",
    monthlyRent: 3600,
    maxOccupants: 3,
    utilitiesIncluded: false,
    estimatedUtilities: { electricity: 800, water: 200, internet: 0 },
    distanceToCampusKm: 8.5,
    fareOneWay: 25,
    amenities: ["Quiet", "Kitchen"],
  },
  {
    id: "bh-009",
    name: "Badas Family Annex",
    barangay: "Badas",
    monthlyRent: 5800,
    maxOccupants: 4,
    utilitiesIncluded: false,
    estimatedUtilities: { electricity: 1300, water: 340, internet: 1100 },
    distanceToCampusKm: 4.1,
    fareOneWay: 18,
    amenities: ["Wi-Fi ready", "Own CR", "Parking"],
  },
  {
    id: "bh-010",
    name: "Tagabakid Student Flats",
    barangay: "Tagabakid",
    monthlyRent: 6900,
    maxOccupants: 5,
    utilitiesIncluded: false,
    estimatedUtilities: { electricity: 1600, water: 400, internet: 1200 },
    distanceToCampusKm: 5.3,
    fareOneWay: 20,
    amenities: ["Kitchen", "Laundry", "Study area"],
  },
  {
    id: "bh-011",
    name: "Cabuaya Budget Rooms",
    barangay: "Cabuaya",
    monthlyRent: 3200,
    maxOccupants: 2,
    utilitiesIncluded: false,
    estimatedUtilities: { electricity: 700, water: 180, internet: 0 },
    distanceToCampusKm: 9.8,
    fareOneWay: 28,
    amenities: ["Shared CR"],
  },
  {
    id: "bh-012",
    name: "Mati Bayview Dorm",
    barangay: "Central",
    monthlyRent: 10500,
    maxOccupants: 6,
    utilitiesIncluded: true,
    estimatedUtilities: { electricity: 0, water: 0, internet: 0 },
    distanceToCampusKm: 1.4,
    fareOneWay: 12,
    amenities: ["Aircon", "Wi-Fi included", "Kitchen", "Laundry", "Parking"],
  },
];
